//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.11 at 02:28:19 PM EEST 
//


package com.nokia.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nokia.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nokia.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link Config.Actions }
     * 
     */
    public Config.Actions createConfigActions() {
        return new Config.Actions();
    }

    /**
     * Create an instance of {@link Config.Extensions }
     * 
     */
    public Config.Extensions createConfigExtensions() {
        return new Config.Extensions();
    }

    /**
     * Create an instance of {@link Config.Order }
     * 
     */
    public Config.Order createConfigOrder() {
        return new Config.Order();
    }

    /**
     * Create an instance of {@link Config.Actions.Action }
     * 
     */
    public Config.Actions.Action createConfigActionsAction() {
        return new Config.Actions.Action();
    }

    /**
     * Create an instance of {@link Config.Extensions.Extension }
     * 
     */
    public Config.Extensions.Extension createConfigExtensionsExtension() {
        return new Config.Extensions.Extension();
    }

}
